/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    streams: Stream;
    creators: Creator;
    pages: Page;
    creators1: Creators1;
    'Stream-Analytics': StreamAnalytic;
    streamanalytics1: Streamanalytics1;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    streams: StreamsSelect<false> | StreamsSelect<true>;
    creators: CreatorsSelect<false> | CreatorsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    creators1: Creators1Select<false> | Creators1Select<true>;
    'Stream-Analytics': StreamAnalyticsSelect<false> | StreamAnalyticsSelect<true>;
    streamanalytics1: Streamanalytics1Select<false> | Streamanalytics1Select<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streams".
 */
export interface Stream {
  id: string;
  title: string;
  streamUrl: string;
  platform: 'youtube' | 'twitch' | 'kick' | 'rumble' | 'other';
  creator: string | Creator;
  /**
   * Auto-updated based on platform API
   */
  isLive?: boolean | null;
  /**
   * Current viewer count
   */
  viewerCount?: number | null;
  /**
   * When the stream started
   */
  startedAt?: string | null;
  thumbnail?: (string | null) | Media;
  featuredImage?: (string | null) | Media;
  /**
   * When the stream ended
   */
  endedAt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators".
 */
export interface Creator {
  id: string;
  /**
   * Auto-filled from channel URL
   */
  channelName?: string | null;
  platform: 'youtube' | 'twitch' | 'kick' | 'rumble' | 'other';
  channelUrl: string;
  /**
   * Auto-extracted YouTube channel ID
   */
  channelId?: string | null;
  channelLogo?: (string | null) | Media;
  /**
   * Auto-filled from platform
   */
  description?: string | null;
  fetchedLogoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators1".
 */
export interface Creators1 {
  id: string;
  /**
   * Auto-filled from YouTube
   */
  channelName?: string | null;
  /**
   * Select the streaming platform
   */
  platform: 'youtube' | 'twitch' | 'kick' | 'rumble' | 'other';
  /**
   * Paste a YouTube channel URL or video URL
   */
  channelUrl?: string | null;
  /**
   * Auto-extracted channel ID
   */
  channelId?: string | null;
  /**
   * Auto-uploaded from YouTube
   */
  channelLogo?: (string | null) | Media;
  /**
   * Auto-filled from YouTube
   */
  description?: string | null;
  fetchedLogoUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Stream-Analytics".
 */
export interface StreamAnalytic {
  id: string;
  stream: string | Stream;
  creator: string | Creators1;
  /**
   * Denormalized for faster filtering
   */
  platform: 'youtube' | 'twitch' | 'kick' | 'rumble';
  /**
   * Viewer count at different times during stream
   */
  viewerSnapshots?:
    | {
        timestamp: string;
        viewerCount: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Highest viewer count during stream
   */
  peakViewer?: number | null;
  /**
   * Average viewer count during stream
   */
  averageViewers?: number | null;
  startedAt: string;
  /**
   * When the stream ended (null if still live)
   */
  endedAt?: string | null;
  /**
   * Stream duration in minutes
   */
  duration?: number | null;
  /**
   * Number of viewer snapshots taken
   */
  totalSnapshots?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streamanalytics1".
 */
export interface Streamanalytics1 {
  id: string;
  stream: string | Stream;
  creator?: (string | null) | Creators1;
  /**
   * Stream title (stored for quick access)
   */
  streamTitle: string;
  /**
   * Stream URL (stored for quick access)
   */
  streamUrl?: string | null;
  /**
   * Thumbnail URL (stored for quick access)
   */
  thumbnailUrl?: string | null;
  /**
   * Creator channel name (stored for quick access)
   */
  creatorName: string;
  /**
   * Denmormalize for faster searching
   */
  platform: 'youtube' | 'twitch' | 'kick' | 'rumble' | 'others';
  /**
   * Highest viewerCount from snapshots
   */
  peakViewer?: number | null;
  /**
   * Average viewer count from influxdb
   */
  averageViewers?: number | null;
  startedAt: string;
  /**
   * When the stream ended (null if still live)
   */
  endedAt?: string | null;
  /**
   * Stream duration in minutes
   */
  duration?: number | null;
  /**
   * Last time analytics were calculated
   */
  lastUpdated?: string | null;
  /**
   * Is stream currently live
   */
  isLive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'streams';
        value: string | Stream;
      } | null)
    | ({
        relationTo: 'creators';
        value: string | Creator;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'creators1';
        value: string | Creators1;
      } | null)
    | ({
        relationTo: 'Stream-Analytics';
        value: string | StreamAnalytic;
      } | null)
    | ({
        relationTo: 'streamanalytics1';
        value: string | Streamanalytics1;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streams_select".
 */
export interface StreamsSelect<T extends boolean = true> {
  title?: T;
  streamUrl?: T;
  platform?: T;
  creator?: T;
  isLive?: T;
  viewerCount?: T;
  startedAt?: T;
  thumbnail?: T;
  featuredImage?: T;
  endedAt?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators_select".
 */
export interface CreatorsSelect<T extends boolean = true> {
  channelName?: T;
  platform?: T;
  channelUrl?: T;
  channelId?: T;
  channelLogo?: T;
  description?: T;
  fetchedLogoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creators1_select".
 */
export interface Creators1Select<T extends boolean = true> {
  channelName?: T;
  platform?: T;
  channelUrl?: T;
  channelId?: T;
  channelLogo?: T;
  description?: T;
  fetchedLogoUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Stream-Analytics_select".
 */
export interface StreamAnalyticsSelect<T extends boolean = true> {
  stream?: T;
  creator?: T;
  platform?: T;
  viewerSnapshots?:
    | T
    | {
        timestamp?: T;
        viewerCount?: T;
        id?: T;
      };
  peakViewer?: T;
  averageViewers?: T;
  startedAt?: T;
  endedAt?: T;
  duration?: T;
  totalSnapshots?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streamanalytics1_select".
 */
export interface Streamanalytics1Select<T extends boolean = true> {
  stream?: T;
  creator?: T;
  streamTitle?: T;
  streamUrl?: T;
  thumbnailUrl?: T;
  creatorName?: T;
  platform?: T;
  peakViewer?: T;
  averageViewers?: T;
  startedAt?: T;
  endedAt?: T;
  duration?: T;
  lastUpdated?: T;
  isLive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}